### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by FTRobert** [wotschofsky/discord-live-translator#33]
As the title says, it is offline, more I can't make of it, it just doesn't react to commands and is shows offline
Thanks in advance if this gets fixed

**Comment by TriForceX** [comment]
Why the bot is offline very often?

**Comment by feliskio** [comment]
Hi, please excuse the inconvenience!
The current version is not production ready and I wasn't too happy with the quality of the previous version. An updated version of the bot should be available soon and the hosted version back online.
Please keep in mind that this is purely a side-project of mine offered entirely for free. Thank you!

**Comment by justgosh** [comment]
Please keep it live even if the quality is low, folks still find it useful.  Add a note that it's in beta testing.

**Comment by TriForceX** [comment]
> Hi, please excuse the inconvenience! The current version is not production ready and I wasn't too happy with the quality of the previous version. An updated version of the bot should be available soon and the hosted version back online. Please keep in mind that this is purely a side-project of mine offered entirely for free. Thank you!

sure! im not complaining, ive been wondering why, i didnt know it was hosted by you, thats totally understandable. Im new on Discord bots, so i was looking for a way to host this one myself.

**Comment by CptTeach1** [comment]
Hey hey
The bot is currently offline. What’s the outlook ? I’m really interested by the voice translation feature 
Thx for your free work, much appreciated

**Comment by wotschofsky** [comment]
Same as #39 

I think I found a solution though: https://x.com/wotschofsky/status/1818643753940193662
