### ISSUE TITLE
problems with setting up Docker

### ISSUE THREAD

**Issue by karwai-myfirst** [wotschofsky/discord-live-translator#41]
Tried to setup Docker and host it myself as you suggested, the docker engine is running fine
the command you shared didn't work, can you help me with this? thanks
![image](https://github.com/wotschofsky/discord-live-translator/assets/114892388/dcc5e604-6d32-4495-a626-4c12eb5b0012)

Also can you provide an example for the .env file?

**Comment by wotschofsky** [comment]
Hi @karwai-myfirst , thanks for bringing this to my attention!
Turns out the command parameters were in the wrong order. Here's the corrected version: `docker compose -f docker-compose.prod.yml up -d`
