### ISSUE TITLE
ERR_PNPM_CANNOT_DEPLOY

### ISSUE THREAD

**Issue by BlackReaper33** [wotschofsky/discord-live-translator#44]
```
user:/home/user/discord-live-translator# docker exec discord-live-translator-bot-1 pnpm deploy
OCI runtime exec failed: exec failed: unable to start container process: exec: "pnpm": executable file not found in $PATH: unknown
user:/home/user/discord-live-translator# pnpm deploy
 ERR_PNPM_CANNOT_DEPLOY  A deploy is only possible from inside a workspace
```

pnpm doesnt work like yarn please fix

**Comment by wotschofsky** [comment]
Hi @BlackReaper33, thanks for bringing this to my attention!
I have adjusted the recommended commands accordingly:
`docker exec discord-live-translator-bot-1 pnpm run deploy`

**Comment by BlackReaper33** [comment]
user:/home/user/discord-live-translator# docker exec discord-live-translator-bot-1 pnpm run deploy
```OCI runtime exec failed: exec failed: unable to start container process: exec: "pnpm": executable file not found in $PATH: unknown```
user:/home/user/discord-live-translator# pnpm deploy
``` ERR_PNPM_CANNOT_DEPLOY  A deploy is only possible from inside a workspace```
