### ISSUE TITLE
Not working, dead silent

### ISSUE THREAD

**Issue by BlackReaper33** [wotschofsky/discord-live-translator#56]
So i ran all the commands as stated except ```pnpm run deploy```
Bot joins the voice chat i input the start command and choose my target language and after that bot is dead silent 
Help

**Comment by wotschofsky** [comment]
Hi @BlackReaper33, can you please post (a) the logs from the bot and (b) a screenshot of the bot has on your server

**Comment by BlackReaper33** [comment]
where will i find logs of the bot?

**Comment by BlackReaper33** [comment]
there are no logs @wotschofsky 
![2](https://github.com/wotschofsky/discord-live-translator/assets/84635243/78ee4dc9-e246-4493-9fa7-6ecdb716157e)

**Comment by wotschofsky** [comment]
If you run the `docker compose` command without `-d` (detached mode), you will see the logs from the individual containers.

**Comment by BlackReaper33** [comment]
im not sure whats wrong
![2](https://github.com/wotschofsky/discord-live-translator/assets/84635243/c433ea01-0f7f-4f54-958a-7850147daf5b)

**Comment by wotschofsky** [comment]
Thank you for posting this! It looks like this is a duplicate of #42, therefore I'll close this issue. Please feel free to watch the other issue.
