### ISSUE TITLE
The bot appears to be offline.

### ISSUE THREAD

**Issue by databoose** [wotschofsky/discord-live-translator#89]
![image](https://github.com/user-attachments/assets/1b1eb417-5c31-4ee5-ac65-b1a675720e8c)

Is this project still active? It seems like the best translator bot so far that i've used, even with some of the premium plans that other bots offer.

**Comment by databoose** [comment]
Also i would like to add that the instructions for hosting the bot with docker locally did not work, i set up the .env file as directed, renamed it to .env and ran the following command, and docker didn't recognize a lot of the flags provided within the command in the instructions.

**Comment by wotschofsky** [comment]
Hi, yes, that's unfortunately true. Please check for #39 for details :)
